spring:
    # application name
    application.name: userservice

    # datasource properties
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    # jpa properties
    jpa:
        hibernate.ddl-auto: update
        show-sql: true

    # kafka properties
    kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

# eureka-client configuration
eureka.client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_SERVER_URL}

server.port: ${SERVER_PORT}
me.sridharpatil.ecom.userservice.notification.type: emailNotificationSender
#application:
#    configure:
#        notification.type: emailNotificationSender

management.endpoints.web.exposure.include: mappings

